name: Test
'on':
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    name: Test
    uses: escalate/github-actions-workflows/.github/workflows/test.yml@master

  cookiecutter:
    name: Cookiecutter
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set up Python 3.x
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install cookiecutter
        run: |
          pip3 install --disable-pip-version-check cookiecutter

      - name: Generate test project
        run: |
          make test

      - name: Upload generated test project
        uses: actions/upload-artifact@v7
        with:
          name: cookiecutter-test-project
          path: test/
